FROM node:20.20.0-alpine AS builder

WORKDIR /app
# ARG VITE_GOOGLE_CLIENT_ID
# ARG VITE_BACKEND_URL

# ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
# ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
COPY ./package*.json ./

RUN npm install
COPY . .


RUN npm run build

FROM nginx:alpine as production
COPY --from=builder /app/dist /usr/share/nginx/html/
EXPOSE 5173
CMD ["nginx","-g","daemon off;"]