FROM node:20.20.0 AS builder
WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20 AS production
WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY --from=builder /app/dist ./dist
EXPOSE 8001
CMD ["npm", "run", "start"]
